# Generated by Django 4.1 on 2022-08-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('Author', models.CharField(max_length=50)),
            ],
        ),
    ]
