# Generated by Django 4.1 on 2022-08-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
